jpackage ^
	--input .\jar\ ^
	--dest .\downloads\ ^
	--name Mars_2241_0828 ^
	--icon .\images\mars.ico ^
	--main-jar Mars_2241_0828.jar ^
	--type exe ^
	--app-version "4.5.41828" ^
	--vendor "com.jfbillingsley" ^
	--win-menu ^
	--verbose