.eqv DISPLAY_W        128
.eqv DISPLAY_H        128
.eqv DISPLAY_W_SHIFT    7

.eqv DISPLAY_MODE_MS_SHIFT  16
.eqv DISPLAY_MODE_ENHANCED  0x100
.eqv DISPLAY_MODE_FB_ENABLE 1
.eqv DISPLAY_MODE_TM_ENABLE 2

.eqv DISPLAY_CTRL           0xFFFF0000
.eqv DISPLAY_SYNC           0xFFFF0004
.eqv DISPLAY_PALETTE_RESET  0xFFFF0008

.eqv DISPLAY_FB_CLEAR       0xFFFF0010
.eqv DISPLAY_FB_IN_FRONT    0xFFFF0014
.eqv DISPLAY_FB_PAL_OFFS    0xFFFF0018

.eqv DISPLAY_TM_SCX         0xFFFF0020
.eqv DISPLAY_TM_SCY         0xFFFF0024
.eqv DISPLAY_TM_PAL_OFFS    0xFFFF0028

.eqv DISPLAY_KEY_HELD       0xFFFF0040
.eqv DISPLAY_KEY_PRESSED    0xFFFF0044
.eqv DISPLAY_KEY_RELEASED   0xFFFF0048
.eqv DISPLAY_MOUSE_X        0xFFFF004C
.eqv DISPLAY_MOUSE_Y        0xFFFF0050
.eqv DISPLAY_MOUSE_HELD     0xFFFF0054
.eqv DISPLAY_MOUSE_PRESSED  0xFFFF0058
.eqv DISPLAY_MOUSE_RELEASED 0xFFFF005C

.eqv DISPLAY_PALETTE_RAM    0xFFFF0C00
.eqv DISPLAY_FB_RAM         0xFFFF1000

.eqv DISPLAY_TM_TABLE       0xFFFF5000
.eqv DISPLAY_SPR_TABLE      0xFFFF5800
.eqv DISPLAY_TM_GFX         0xFFFF6000
.eqv DISPLAY_SPR_GFX        0xFFFFA000

.eqv MOUSE_LBUTTON 1
.eqv MOUSE_RBUTTON 2
.eqv MOUSE_MBUTTON 4

# Classic color palette indexes in the default palette
.eqv COLOR_BLACK       64
.eqv COLOR_RED         65
.eqv COLOR_ORANGE      66
.eqv COLOR_YELLOW      67
.eqv COLOR_GREEN       68
.eqv COLOR_BLUE        69
.eqv COLOR_MAGENTA     70
.eqv COLOR_WHITE       71
.eqv COLOR_DARK_GREY   72
.eqv COLOR_DARK_GRAY   72
.eqv COLOR_BRICK       73
.eqv COLOR_BROWN       74
.eqv COLOR_TAN         75
.eqv COLOR_DARK_GREEN  76
.eqv COLOR_DARK_BLUE   77
.eqv COLOR_PURPLE      78
.eqv COLOR_LIGHT_GREY  79
.eqv COLOR_LIGHT_GRAY  79